name: bicount
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dartz: ^0.10.1
  go_router: ^16.0.0
  equatable: ^2.0.7
  supabase_flutter: ^2.9.1
  toastification: ^3.0.3
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  hugeicons: ^0.0.11
  currency_picker: ^2.0.21
  loading_animation_widget: ^1.3.0
  http_parser: ^4.1.2
  image_picker: ^1.2.0
  mime: ^2.0.0
  path: ^1.9.1
  flutter_skeleton_ui: ^0.0.6
  pie_chart_sz: ^1.1.1
  connectivity_plus: ^7.0.0
  internet_connection_checker: ^1.0.0+1
  uuid: ^4.5.1

  #For the offline mode
  brick_offline_first_with_supabase: ^2.1.0
  sqflite: ^2.4.2
  brick_sqlite: ^4.1.0
  brick_supabase: ^2.1.0
  sqflite_common: ^2.5.6
  brick_core: ^2.0.0
  flutter_native_splash: ^2.4.7
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.1
  brick_offline_first_with_supabase_build: ^2.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/memoji/
    - assets/icons/
    - assets/app_icon/
